### ISSUE TITLE
公众号支付生成的签名有问题

### ISSUE THREAD

**Issue by JeffreyBool** [smartwalle/wxpay#12]
公众号支付生成的签名有问题

正常需要根据 "package" => "prepay_id=wx232012162918612d7ff41f831267443400" 返回的值重新做一遍签名

**Comment by JeffreyBool** [comment]
https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=7_7&index=6

**Comment by smartwalle** [comment]
看一下 order.go 里面的 63 行，有一个 JSAPIPay 的方法，是做了相关的操作的，不知道是不是你想的那个。

**Comment by JeffreyBool** [comment]
XML syntax error on line 6: element <hr> closed by </body>

![image](https://user-images.githubusercontent.com/24415888/61761238-ab60ed80-ae00-11e9-9bb3-7472ea96394c.png)

**Comment by smartwalle** [comment]
out trade no 换一下，多试几次，sandbox 环境不稳定

**Comment by JeffreyBool** [comment]
貌似 
![image](https://user-images.githubusercontent.com/24415888/61763093-b585ea80-ae06-11e9-906d-d7bf5aab3d11.png)

AppId 为空

**Comment by smartwalle** [comment]
你有提供吗？

**Comment by JeffreyBool** [comment]
这里明显看测试用例也没用提供。 看以前直接去 Client 获取 app_id

**Comment by JeffreyBool** [comment]
![image](https://user-images.githubusercontent.com/24415888/61763320-96d42380-ae07-11e9-989b-975a81ba86f3.png)
 我不懂这里为什么要加个 app_id
