### ISSUE TITLE
小程序支付提示签名错误

### ISSUE THREAD

**Issue by gaojiankang** [smartwalle/wxpay#18]
请看截图
https://s1.ax1x.com/2020/08/21/dNCJNq.png

**Comment by smartwalle** [comment]
我刚试了，是正常的，确认一下你的版本是不是最新的，用  v2.0.8 版本， go  get  github.com/smartwalle/wxpay/v2

**Comment by gaojiankang** [comment]
我重新检查了一下，是我的api key错了，抱歉哈。。
